[package]
name = "noor"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph = { git = "https://github.com/asibahi/ab-glyph.git" }
harfbuzz_rs = "2.0.1"
icu_segmenter = "1.4.0"
# harfbuzz_rs = { git = "https://github.com/harfbuzz/harfbuzz_rs.git" }
image = { version = "0.25", default-features = false, features = [
    "png",
    "jpeg",
    "rayon",
] }
imageproc = "0.24"
itertools = "0.12.1"
pathfinding = "4.9.1"
resvg = "0.41.0"
